export const mockData = {
  schedule: [
    {
      id: 1,
      day: "Monday",
      time: "09:00",
      subject: "Mathematics",
      teacher: "Mr. Smith",
    },
    {
      id: 2,
      day: "Monday",
      time: "10:00",
      subject: "Science",
      teacher: "Ms. Johnson",
    },
  ],
  grades: [
    {
      id: 1,
      student: "John Doe",
      subject: "Mathematics",
      grade: "A",
      date: "2025-06-01",
    },
    {
      id: 2,
      student: "Jane Smith",
      subject: "Science",
      grade: "B+",
      date: "2025-06-02",
    },
  ],
  videos: [
    {
      id: 1,
      title: "Algebra Basics",
      url: "https://example.com/video1",
      subject: "Mathematics",
    },
    {
      id: 2,
      title: "Physics Intro",
      url: "https://example.com/video2",
      subject: "Science",
    },
  ],
  assignments: [
    {
      id: 1,
      title: "Math Homework 1",
      dueDate: "2025-07-01",
      subject: "Mathematics",
    },
  ],
  messages: [
    {
      id: 1,
      sender: "Mr. Smith",
      content: "Please complete your assignments by Friday.",
      date: "2025-06-27",
    },
  ],
  conversations: [
    {
      id: 1,
      with: "Ms. Johnson",
      lastMessage: "Can we discuss the project?",
      time: "2025-06-27 14:00",
    },
  ],
  students: [
    {
      id: "AD9892434",
      rollNo: 35013,
      name: "Janet",
      avatar: "/path/to/janet.png",
      class: "III",
      section: "A",
      gender: "Female",
      status: "Active",
      dateOfJoin: "25 Mar 2024",
      dob: "10 Jan 2015",
    },
    {
      id: "AD9892433",
      rollNo: 35013,
      name: "Joann",
      avatar: "/path/to/joann.png",
      class: "IV",
      section: "B",
      gender: "Male",
      status: "Active",
      dateOfJoin: "18 Mar 2024",
      dob: "19 Aug 2014",
    },
    {
      id: "AD9892432",
      rollNo: 35011,
      name: "Kathleen",
      avatar: "/path/to/kathleen.png",
      class: "II",
      section: "A",
      gender: "Female",
      status: "Active",
      dateOfJoin: "14 Mar 2024",
      dob: "05 Dec 2017",
    },
    {
      id: "AD9892431",
      rollNo: 35010,
      name: "Gifford",
      avatar: "/path/to/gifford.png",
      class: "I",
      section: "B",
      gender: "Male",
      status: "Active",
      dateOfJoin: "27 Feb 2024",
      dob: "22 Mar 2018",
    },
    {
      id: "AD9892430",
      rollNo: 35009,
      name: "Lisa",
      avatar: "/path/to/lisa.png",
      class: "II",
      section: "B",
      gender: "Female",
      status: "Inactive",
      dateOfJoin: "13 Feb 2024",
      dob: "13 May 2017",
    },
    {
      id: "AD9892429",
      rollNo: 35008,
      name: "Ralph",
      avatar: "/path/to/ralph.png",
      class: "III",
      section: "B",
      gender: "Male",
      status: "Active",
      dateOfJoin: "11 Feb 2024",
      dob: "20 Jun 2015",
    },
  ],
};
